"""Add unique constraint to transactions

Revision ID: 1fedb7c25f47
Revises: f70ad5cdd5d0
Create Date: 2025-03-15 12:13:07.936905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fedb7c25f47'
down_revision: Union[str, None] = 'f70ad5cdd5d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_transaction_batch', 'transactions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_transaction_batch', 'transactions', ['user_id', 'amount', 'merchant', 'date', 'batch_id'])
    # ### end Alembic commands ###
