"""Updated models

Revision ID: ef2b08230d26
Revises: 0af7f773c12e
Create Date: 2025-03-03 11:55:56.871541

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef2b08230d26'
down_revision: Union[str, None] = '0af7f773c12e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('merchant', sa.String(), nullable=False))
    op.add_column('transactions', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'date')
    op.drop_column('transactions', 'merchant')
    # ### end Alembic commands ###
