"""Add unique constraint to transactions

Revision ID: f70ad5cdd5d0
Revises: 2af651eb99ce
Create Date: 2025-03-15 11:23:03.578189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f70ad5cdd5d0'
down_revision: Union[str, None] = '2af651eb99ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
